### ISSUE TITLE
启动报错了，请问大佬如何解决？

### ISSUE THREAD

**Issue by matrixbingo** [wangJacker/ant-design-pro-V5-multitab#1]
![image](https://user-images.githubusercontent.com/11989717/121768794-aba03880-cb92-11eb-9a49-131d16b1fbb0.png)

启动报错了，请问大佬如何解决？

**Comment by wangJacker** [comment]
这个是node 包安装掉包的问题，官方推荐使用tyarn 管理 用yarn 也行 ，个人不推荐直接使用npm。解决方法：删除本地node_modules，重新执行tyarn install 或者yarn install
