### ISSUE TITLE
👑 [需求] 请问有没有在umi-plugin-qiankun 的实现

### ISSUE THREAD

**Issue by leehomeok** [wangJacker/ant-design-pro-V5-multitab#2]
### 🥰 需求描述
现在公司用的qiankun + umi 微前端框架，也迫切需要keep-alive + 多tab功能

**Comment by listenecho** [comment]
大佬这个问题解决了吗?

**Comment by wangJacker** [comment]
其实这个应该也是一样的只是 不在使用状态来管理当前激活的tab 使用路由路径来管理当前激活路由状态，利用状态辅助记录所有的已经打开的tab， 我觉得理论上是可以做的
